# Survey Monkey

# Configuration

The first code block ensures that Python is able to correctly locate the modules used for this pipeline

In [1]:
import sys
import os

sys.path.append(f'{os.getcwd()}/src')

In [2]:
surveyId = '314840976'

### Extract from Survey Monkey

Survey data is extracted from the Survey Monkey API with the raw data stored in JSON files in `/datalake`

In [3]:
from modules.survey_monkey import surveyMonkey

# surveyMonkey(surveyId)

### Transform data to normalized structured and load to database

This stage takes the extract from Survey Monkey, transforming it and loading normalized relational database structure

In [4]:
from modules.normalize import transformToNormalizedDb

transformToNormalizedDb(surveyId)

### Transform

This transformation stage provides domain-specific transformations to the data, combining it back into a single view.

These transformations include:
- Combine the count of followers across different social networks
- Calculate the current age based on date of birth

The data is then denormalised ready for loading and data exploration

In [5]:
from modules.survey_transforms.mfm_transforms import transformMfmTesters

transformedData = transformMfmTesters(surveyId)

WARNING:root:Unable to parse follower count string 256. TikTok over 1k and over 60k likes
WARNING:root:Unable to parse follower count string Facebook Page - Facebook.com/itsaliceannx
12k
WARNING:root:Unable to parse follower count string 3.5k on business account.
300 on personal.
WARNING:root:Unable to parse follower count string 7 (started this today) first video surpassed 1k views
WARNING:root:Unable to parse follower count string 317 and 10.3k likes
WARNING:root:Unable to parse follower count string 890 - as I have it on private
1.5k - my husband
WARNING:root:Unable to parse follower count string 300+ on milas
2000+ on mine
WARNING:root:Unable to parse follower count string Staerck:1,317
Hapgood:256
WARNING:root:Unable to parse follower count string 2k
5.7k
WARNING:root:Unable to parse follower count string 4.7k
186
WARNING:root:Unable to parse follower count string 380
Looking to grow and post baby content
WARNING:root:Unable to parse follower count string 650
My partner has nearly 17,000
WARNING:root:Unable to parse follower count string Sandrarantz - 31,000
Rantzfam - 5,500
Benrantz - 152,000
WARNING:root:Unable to parse follower count string 200 (ish) on my private account. I have a home interiors account with around 3k and a dog instagram account with around 5k.
WARNING:root:Unable to parse follower count string 441 (personal).
10.6k (business)
WARNING:root:Unable to parse follower count string Karly_knight17
WARNING:root:Unable to parse follower count string sophiahy85 (1,947)
prince_tyler2020 (728)
charmingseoul (781)
WARNING:root:Unable to parse follower count string 2617 followers
150.0k likes
WARNING:root:Unable to parse follower count string 2500
I have some videos with as much as 3.5M views
WARNING:root:Unable to parse follower count string geewray: 835
iamgeorgiawray: 1133
WARNING:root:Unable to parse follower count string 7.5k on Instagram and 8.8k on tiktok
WARNING:root:Unable to parse follower count string 8.5k on 1 account
4.6k on 1 account
470 on another
WARNING:root:Unable to parse follower count string Personal - 400

Supermummy secrets - over 5k

Lifestyle home & Christmas Inspired - over 8k
WARNING:root:Unable to parse follower count string 1.9k
5.7k
WARNING:root:Unable to parse follower count string Private-400
Public-800
WARNING:root:Unable to parse follower count string 540

Instagram 940 tara_crichton
WARNING:root:Unable to parse follower count string 3.2k Englishian
7.1k TheStyleRawr
WARNING:root:Unable to parse follower count string @englishian - over 1k
@TheStyleRawr - almost 2k
WARNING:root:Unable to parse follower count string 196 followers

55.7k likes
WARNING:root:Unable to parse follower count string @terracenumber9 2000 followers

### Load

The final load stage uses pandas to load a dataframe object into CSV, JSON and Excel file formats.

In [6]:
from modules.pandas import pandasLoad
from modules.survey_transforms.mfm_transforms import mfmColumns

dataColumns = mfmColumns(surveyId)

dataframe = pandasLoad(transformedData, dataColumns)

dataframe.head(10)

,What is the age of your youngest child?,What is the age of your next child (<strong>child 2</strong>)?,Aggregated Follower Count,What is the date of birth of your youngest child?,Which best describes your ethnic background?,Which sleep products is your baby or child/ren using ? Please select all that apply,How would you describe your family? Please select all that apply,Does your car have ISOFIX fittings?,How many children do you have?,Are you an influencer or blogger? Please select all that apply,Do you or will you use reusable nappies?,Which of the following best describe the ethnic group of <strong>your family</strong> (eg partner and/or children)? Please select all that apply,Do any members of your household have... Please select all that apply,Do any members of your household follow a specific diet? Please select all that apply,Please could you give us a few more details and who in your family experiences this,Please write a short review (no more than 100 words) about a pregnancy OR parenting product you've used. We're looking for your feedback on what you liked and didn't like about it. We may use this review to help us decide whether or not to choose you as a tester,What is your contact email?,"What is the name of your Facebook account? If possible, please do NOT include @ in your answer. Please note, we need this so we can recognise you when you request to join the MFM Top Testers Club",Have you or your partner used or are you planning to use a breast pump?,"What is your Instagram handle? If possible, please do NOT include @ in your answer. Please skip if you'd rather not say",Please tell us your first name,Do you have any pets living with you at home? Please select all that apply,How would you describe yourself...,"Does anyone in your household have food allergies, intolerances or sensitivities? Please select all that apply","I understand that if I am sent a product to test, I will provide MadeForMums with the required feedback within the specified deadline, or I will have to return the product(s) in their original and unused condition or be charged the RRP for it.",Do you have an Instagram account?,How important to you is choosing eco-friendly/sustainable parenting products?,Which of these best describes the area you live in?,"Are you currently using, or have you used in the past, a dummy or soother for your baby or child?",Do you or your family have any skincare conditions? Please select all that apply,What is your annual household income before tax?,Roughly how many followers do you have on your Facebook account? Please skip if you'd rather not say,Do you have any additional information you'd like to tell us about you or your children? (optional),Roughly how many followers do you have on your Instagram account? Please skip if you'd rather not say,Please can you tell us the make of your car,Please tell us your surname,What is the first name of your youngest child?,What is your mobile number? (This is so we can contact you if there are any queries about delivering a product to you or following up on feedback),What is your full postal address?,Do you have a TikTok account?,Do you have any children?,Does your baby or child suck their thumb?,"I understand and agree that if I am chosen to be a product tester, my name, postal address and phone number may be shared with the company who will be despatching the product to me (we will only pass this information on if it's essential for delivery)",Do you live in a:,Would you describe your youngest child as...,Do you have a Facebook account? Please note you will need a Facebook account in order to join the MFM Top Testers Club Facebook group,Do you have a Twitter account?,Do you have a YouTube channel?,Please tell us which age group you fall into,Which of the following best describe <strong>your</strong> ethnic group or background? This is just about you - we’ll ask about your family’s ethnic backgrounds in the next question,What is your current occupation? (If you're on mat leave please tell us what you were doing beforehand),Please tell us the model of your car,What is the date of birth of your next child (<strong>child 2</strong>)?,Which best describes your famiy's White ethnic background?,Do you have or are you expecting twins or other multiples?,"I understand and agree that, if I am chosen as a product tester, MadeForMums may contact me (via WhatsApp, SMS, etc) using the phone number or email address I have provided if there are any issues with the product I am testing and/or product despatch and/or my feedback.","When it comes to feeding your baby, currently/previously/in the future are you or your partner...",How did you hear about being a MFM Top Testers Club member? Please select all that apply,Which region do you live in?,"If possible, please tell us the year your car was manufactured","I understand and agree that, if I am chosen to be a product tester, MadeForMums may use <strong>my feedback</strong> on the MadeForMums website, on its social channels, in its newsletters and/or other promotional activities, such as coverage in the national press. Use will always be in accordance with our <a href=""https://www.immediate.co.uk/privacy"" rel=""nofollow"" target=""_blank"">Privacy Policy</a>",Have you been involved with MadeForMums before? Please select all that apply,Are you or your partner pregnant?,"With a pushchair, do you or will you have to use stairs or steps (to get to your home, use public transport etc)?",What's their first name?,Would you describe your child (<strong>child 2</strong>) as...,"I understand and agree that, if I am chosen to be a product tester, MadeForMums may use <strong>the pictures I supply</strong> with my feedback on the MadeForMums website, on its social channels, in its newsletters and/or other promotional activities. Use will always be in accordance with our <a href=""https://www.immediate.co.uk/privacy"" rel=""nofollow"" target=""_blank"">Privacy Policy</a>","How much time do you and your family spend outdoors doing physical activities such as country walks, hiking, cycling?","I understand and agree that, if I am chosen to be a member of MadeForMums Top Testers Club, MadeForMums will keep my details (including all of the personal data provided in this registration survey e.g. details about my family, home, health and pregnancy) on its secure server so that it can organise and run the testing, feedback and Top Testers process and can invite me to take part in testing opportunities in the future. Please note: you can ask us to delete your details from our secure server by mailing toptesters@madeformums.com Use will always be in accordance with our <a href=""https://policies.immediate.co.uk/privacy/"" rel=""nofollow"" target=""_blank"">Privacy Policy</a>",Have you used or are you planning to use a running/jogging buggy?,"Have you used or are you planning to use a baby carrier, wrap or sling? Please tick all that apply","I am a registered member of MadeForMums and have registered with the email address I entered earlier on this survey. (This is a requirement for joining the MadeForMums Top Testers Club and will be checked before you can be accepted as a member).<br>If you have not yet registered, you can <a href=""https://www.madeformums.com/account/1/Registration/Register/MadeForMums?utm_source=TTClub&utm_medium=1"" rel=""nofollow"" target=""_blank"">register here</a>.<br>If you have trouble registering, please mail toptesters@madeformums.com",Do you have indoor space to test a large product such as a cot/cotbed?,Do you have outdoor space to test a large product such as a trampoline?,Do you (or someone in your household) have a car?,What is your child's age?,What is your child's date of birth?,"What is your TikTok name? If possible, please do NOT include @ in your answer. Please skip if you'd rather not say",Roughly how many followers do you have on your TikTok account? Please skip if you'd rather not say,What is the first name of your child?,Would you describe your child as...,"What is your Twitter handle? If possible, please do NOT include @ in your answer. Please skip if you'd rather not say",Which best describes your family's Mixed ethnic background?,What is the age of your youngest child?,What is the age of your next child (<strong>child 2</strong>)?,What is the age of your next child (<strong>child 3</strong>)?,What is the date of birth of your youngest child?,What is the first name of your youngest child?,Would you describe your youngest child as...,What is the date of birth of your next child (<strong>child 2</strong>)?,What is their first name?,Would you describe your child (<strong>child 2</strong>) as...,What is the date of birth of your next child (<strong>child 3</strong>)?,What is their first name?,Would you describe your child (<strong>child 3</strong>) as...,Which best describes your family's Asian ethnic background?,Please could you give us a few more details and who in your family experiences this,Which best describes your ethnic background?,Congratulations! When is the due date?,"During pregnancy, are you or your pregnant partner...",What is the name of your YouTube channel? Please skip if you'd rather not say,Roughly how many subscribers do you have to your YouTube channel? Please skip if you'd rather not say,What is the age of your youngest child?,What is the age of your next child (<strong>child 2</strong>)?,What is the age of your next child (<strong>child 3</strong>)?,What is the age of your next child (<strong>child 4</strong>)?,What is the age of your next child (<strong>child 5</strong>)?,What is the date of birth of your youngest child?,Please could you give us a few more details - eg who in your family experiences this,What is the first name of your youngest child?,Roughly how many followers do you have on your Twitter account? Please skip if you'd rather not say,Would you describe your youngest child as...,What is the date of birth of your next child (<strong>child 2</strong>)?,What is their first name?,Would you describe your child (<strong>child 2</strong>) as...,What is the date of birth of your next child (<strong>child 3</strong>)?,What is their first name?,Would you describe your child (<strong>child 3</strong>) as...,What is the date of birth of your next child (<strong>child 4</strong>)?,What is their first name?,Would you describe your child (<strong>child 4</strong>) as...,What is the date of birth of your next child (<strong>child 5</strong>)?,What is their first name?,Would you describe your child (<strong>child 5</strong>) as...,Which best describes your mixed ethnic background?,Which best describes your ethnic background?,Which best describes your family's Black ethnic background?,What is the age of your youngest child?,What is the age of your next child (<strong>child 2</strong>)?,What is the age of your next child (<strong>child 3</strong>)?,What is the age of your next child (<strong>child 4</strong>)?,What is the date of birth of your youngest child?,What is the first name of your youngest child?,Would you describe your youngest child as...,What is the date of birth of your next child (<strong>child 2</strong>)?,What is their first name?,Would you describe your child (<strong>child 2</strong>) as...,What is the date of birth of your next child (<strong>child 3</strong>)?,What is their first name?,Would you describe your child (<strong>child 3</strong>) as...,What is the date of birth of your next child (<strong>child 4</strong>)?,What is their first name?,Would you describe your child (<strong>child 4</strong>) as...,What is the age of your youngest child?,What is the age of your next child (<strong>child 2</strong>)?,What is the age of your next child (<strong>child 3</strong>)?,What is the age of your next child (<strong>child 4</strong>)?,What is the age of your next child (<strong>child 5</strong>)?,What is the date of birth of your youngest child?,What is the first name of your youngest child?,Would you describe your youngest child as...,What is the date of birth of your next child (<strong>child 2</strong>)?,What is their first name?,Would you describe your child (<strong>child 2</strong>) as...,What is the date of birth of your next child (<strong>child 3</strong>)?,What is their first name?,Would you describe your child (<strong>child 3</strong>) as...,What is the date of birth of your next child (<strong>child 4</strong>)?,What is their first name?,Would you describe your child (<strong>child 4</strong>) as...,What is the date of birth of your next child (<strong>child 5</strong>)?,What is their first name?,Would you describe your child (<strong>child 5</strong>) as...,Please give us the details of your additional children (first name and date of birth) for each
Response ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
19018161680,2.0,5.0,1700,03/25/2022,English / Scottish / Welsh / Northern Irish / ...,"Cot, Full-size bed",Two parent family living together,Yes,2,Neither of the above,No,White,None of the above,No special diet,Son and husband have mild eczema in the winter...,Wrap over bodysuits have been a game changer f...,Lornameadows@outlook.com,Lorna J. Meadows,Have used. Probably not anymore due to supply.,@lornameadows4,Lorna,Don't have a pet,Female,No,I agree,Yes - a private one,Quite important,Town/Suburbs,No,Mild eczema,"£50,000-£69,999",1000,Logan is the best big brother to Aurora (aka R...,700,Land Rover,Maxfield,Aurora,07538839734,"11 Follows End, Burntwood, WS7 3Qz, UK",Yes,Yes,Yes - frequently,I understand and agree,House,A girl,Yes - a private one,No,No,25-34,White,Primary School teacher - due to go back to wor...,Discovery,09/22/2019,English / Scottish / Welsh / Northern Irish / ...,No,I understand and agree,Both breast and bottlefeeding,I was recommended the Club by a friend,West Midlands,2018,I understand and agree,"No, not yet",No,No,Logan,A boy,I understand and agree,Fair amount of time,I understand and agree,No,"Baby carrier, Sling",Yes,Yes,Yes - but I'd rather not,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19116376084,2.0,6.0,0,05/30/2022,English / Scottish / Welsh / Northern Irish / ...,"Cot, Full-size bed",Two parent family living together,Yes,2,Neither of the above,No,White,None of the above,No special diet,Eldest son,Joolz aer stroller\r\nIt took a bit of persuad...,Janineekendall@icloud.com,Janine Kendall,NaN,NaN,Janine,Cat,Female,No,I agree,Yes - a private one,Quite important,City,Yes,Moderate eczema,"£50,000-£69,999",NaN,Crazy beautiful boys. The house is mad but ful...,NaN,Peugeot 308,Kendall,Elliot,07973854799,"11 dallington rd , Coundon, Coventry , Cv6 1gb...",No,Yes,No,I understand and agree,House,A boy,Yes - a private one,No,No,35-44,White,Women’s clothing buyer,308,12/28/2017,English / Scottish / Welsh / Northern Irish / ...,No,I understand and agree,Bottlefeeding,I was recommended the Club by a friend,West Midlands,2022,I understand and agree,"Yes, I've been a reviews home tester",No,No,Evan,A boy,I'm happy for MadeForMums to use the pictures ...,Fair amount of time,I understand and agree,Not yet but plan to,"Baby carrier, Wrap",Yes,Yes,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19165976386,NaN,NaN,3020,NaN,NaN,"Cot, Cotbed, Bedside crib, Moses basket, Toddl...",Two parent family living together,Yes,1,Influencer,Yes - currently using,Hispanic-latin,None of the above,No special diet,NaN,I would like to try educational games for fami...,macatriplesss501@gmail.com,SweetdollOfficial,Yes,Sweetdoll_official,Macarena Mercedes,Don't have a pet,Female,No,I agree,Yes - a public one,Quite important,City,Yes,No skincare conditions,"Under £10,000",150,No,2420,Citroën,Salgado De Sanctis,NaN,+41764487123,"Rue du lac 25 D, 2 étage , Renens vd, 1020, Re...",Yes,Yes,Yes - frequently,I understand and agree,House,NaN,Yes - a public one,No,No,35-44,Haipanic-latin,I’m working waitress,Citroën c5,NaN,NaN,No,I understand and agree,Breastfeeding,I was personally invited by a MadeForMums team...,Switzerland,Yes,I understand and agree,"No, not yet",No,Yes - sometimes,NaN,NaN,I understand and agree,As much as we can,I understand and agree,No,Baby carrier,Yes,Yes,Yes,Yes,3.0,11/01/2021,SweetdollOfficial,450,Lea,A girl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13273213134,NaN,NaN,1426,NaN,English / Scottish / Welsh / Northern Irish / ...,Full-size bed,Lone parent family,Yes,1,Neither of the above,Used to use,White,None of the above,Vegetarian,NaN,I can't recommend the weenect GPS tracker high...,Littlebluegem@hotmail.com,https://www.facebook.com/wendyscupcakesuk,Yes,Wendylovescake,Wendy,Tortoise,Female,No,I agree,Yes - a public one,Quite important,Town/Suburbs,No,No skincare conditions,"£30,000-£39,999",728,My 12 year old son is also a young carer. He a...,698,Fiat,Davis,NaN,07368612504,"21B, Arlington Road, Eastbourne, BN21 1DJ, Uni...",Yes,Yes,No,I understand and agree,Flat,NaN,Yes - a public one,No,Yes - a private one,35-44,White,Statistics Manager for a health company,Fiat 500,NaN,English / Scottish / Welsh / Northern Irish / ...,No,I understand and agree,Breastfeeding,I was personally invited by a MadeForMums team...,South East,NaN,I understand and agree,Contributer on any questionnaires or competiti...,No,Yes - regularly,NaN,NaN,I understand and agree,As much as we can,I understand and agree,Yes,"Baby carrier, Wrap, Sling",Yes,Yes,No,Yes,15.0,11/27/2009,NaN,NaN,Oliver,A boy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Validation
from modules.metadata import getExtractMetadata
from modules.sqlSelects import getSurveyResponses

extractCount = getExtractMetadata(surveyId)['response_count']
normalizedLoadCount = len(getSurveyResponses(surveyId))
denormalizedLoadCount = dataframe.shape[0]

print(f'Total records in extract {extractCount}')
print(f'Total records in relational database {normalizedLoadCount}')
print(f'Total records in final load {denormalizedLoadCount}')

if extractCount == normalizedLoadCount == denormalizedLoadCount:
    print('Pipeline complete and validated')

Total records in extract 6170
Total records in relational database 6170
Total records in final load 6170
Pipeline complete and validated

In [ ]:
import pandas as pd

reachAgg = pd.DataFrame(dataframe['Aggregated Follower Count'])
reachAgg.sort_values(by=['Aggregated Follower Count'], ascending=False)

pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.DataFrame(dataframe['Aggregated Follower Count']).describe()

       Aggregated Follower Count
count                    6170.00
mean                     2354.79
std                     49124.12
min                         0.00
25%                         0.00
50%                       280.00
75%                       967.00
max                   2701870.00

In [9]:
from modules.survey_transforms.mfm_transforms import followerCountFromString

tests = [
    {
        'name': 'Basic String',
        'input': '10',
        'expected': 10
    },
    {
        'name': 'Integer',
        'input': 100,
        'expected': 100
    },
    {
        'name': '2.5k string',
        'input': '2.5k',
        'expected': 2500
    },
    {
        'name': '2.5K string',
        'input': '2.5K',
        'expected': 2500 
    },
    {
        'name': '10,000 string',
        'input': '10,000',
        'expected': 10000 
    },
    {
        'name': '1M string',
        'input': '1M',
        'expected': 1000000
    },
    {
        'name': '2.6m string',
        'input': '2.6m',
        'expected': 2600000
    },
    {
        'name': '1,000+ string',
        'input': '1,000+',
        'expected': 1000
    },
    {
        'name': 'Longer string',
        'input': 'Roughly 500',
        'expected': 500
    },
    {
        'name': 'Longer string with handle',
        'input': '@testaccount 10k',
        'expected': 10000
    },
    {
        'name': 'Over string',
        'input': 'Over 200000',
        'expected': 200000
    },
    {
        'name': 'Question string',
        'input': 'I think about 1000?',
        'expected': 1000
    }
]

print(followerCountFromString('''1. 1777
2. 2715
3. 2600
'''))

for test in tests:
    # Run transformation module
    # result = followerCountFromString(test['input'])
    # Check result is as expected
    isExpected = 'Yes ✅' if result == test['expected'] else 'No ⛔️'
    # Check result type is an integer
    isInt = 'Yes ✅' if type(result) == int else 'No ⛔️'

    # print(f'{test['name']}: {test['input']} became {result}. Expected result? {isExpected}. Is integer? {isInt}')

1

NameError: name 'result' is not defined

In [ ]:
from modules.survey_transforms.mfm_transforms import convertDobToAge

# Note: Dates are in US format mm/dd/yyyy!

tests = [
    {
        'input': '01/01/2024',
        'expected': 0
    },
    {
        'input': '06/05/2023',
        'expected': 1
    },
    {
        'input': '12/31/2020',
        'expected': 3
    },
    {
        'input': '09/05/2025',
        'expected': 0
    },
    {
        'input': '09/05/2030',
        'expected': -5
    },
    {
        'input': '09/10/1980',
        'expected': 44
    },
    {
        'input': '08/01/1998',
        'expected': 26
    }
]

for test in tests:
    # Run transformation module
    result = convertDobToAge(test['input'])
    # Check result is as expected
    isExpected = 'Yes ✅' if result == test['expected'] else 'No ⛔️'
    # Check result type is an integer or None
    isInt = 'Yes ✅' if type(result) == int or type(result) == type(None) else 'No ⛔️'

    print(f'{test['input']} became {result} years. Expected result? {isExpected}. Is integer or None? {isInt}')

01/01/2024 became 0 years. Expected result? Yes ✅. Is integer or None? Yes ✅
06/05/2023 became 1 years. Expected result? Yes ✅. Is integer or None? Yes ✅
12/31/2020 became 3 years. Expected result? Yes ✅. Is integer or None? Yes ✅
09/05/2025 became 0 years. Expected result? Yes ✅. Is integer or None? Yes ✅
09/05/2030 became -5 years. Expected result? Yes ✅. Is integer or None? Yes ✅
09/10/1980 became 44 years. Expected result? Yes ✅. Is integer or None? Yes ✅
08/01/1998 became 26 years. Expected result? Yes ✅. Is integer or None? Yes ✅